package com.wncg.dao;

import com.wncg.po.Book;
import com.wncg.po.BookExample;
import com.wncg.po.BookWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    int countByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    int deleteByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    int deleteByPrimaryKey(String bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    int insert(BookWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    int insertSelective(BookWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    List<BookWithBLOBs> selectByExampleWithBLOBs(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    List<Book> selectByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    BookWithBLOBs selectByPrimaryKey(String bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") BookWithBLOBs record, @Param("example") BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") BookWithBLOBs record, @Param("example") BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    int updateByExample(@Param("record") Book record, @Param("example") BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    int updateByPrimaryKeySelective(BookWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(BookWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    int updateByPrimaryKey(Book record);

    //以下代码由用户自己创建

    //通过关键词、全拼、首拼、图书编号查询书籍信息
    @Select("select book_id,book_name,author,quantity from book where book_id like concat(concat('%', #{bookName}), '%') or book_name like concat(concat('%', #{bookName}), '%') or alpha like concat(concat('%', #{bookName}), '%') or phoneticize like concat(concat('%', #{bookName}), '%') ")
    List<BookWithBLOBs> selectBooksByKeyWords(String bookName);
    //通过图书编号或isbn查看书籍详情
    @Select("select * from book where book_id = #{isbn} or isbn = #{isbn}")
    List<BookWithBLOBs> getBookByIsbn(String isbn);
}