package com.wncg.dao;

import com.wncg.po.Manager;
import com.wncg.po.ManagerExample;
import java.util.List;

import org.apache.ibatis.annotations.*;

public interface ManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Sun Apr 09 15:46:46 CST 2017
     */
    int countByExample(ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Sun Apr 09 15:46:46 CST 2017
     */
    int deleteByExample(ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Sun Apr 09 15:46:46 CST 2017
     */
    int deleteByPrimaryKey(Integer managerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Sun Apr 09 15:46:46 CST 2017
     */
    int insert(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Sun Apr 09 15:46:46 CST 2017
     */
    int insertSelective(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Sun Apr 09 15:46:46 CST 2017
     */
    List<Manager> selectByExample(ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Sun Apr 09 15:46:46 CST 2017
     */
    Manager selectByPrimaryKey(Integer managerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Sun Apr 09 15:46:46 CST 2017
     */
    int updateByExampleSelective(@Param("record") Manager record, @Param("example") ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Sun Apr 09 15:46:46 CST 2017
     */
    int updateByExample(@Param("record") Manager record, @Param("example") ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Sun Apr 09 15:46:46 CST 2017
     */
    int updateByPrimaryKeySelective(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Sun Apr 09 15:46:46 CST 2017
     */
    int updateByPrimaryKey(Manager record);

    @Select("select * from manager where manager=#{manager}")
    List<Manager> loginIn(@Param(value = "manager") String manager);

    @Insert("insert into manager(manager,password) values(#{manager}, #{password})")
    void addManager(@Param(value = "manager") String manager,@Param(value = "password") String password);

    @Update("update manager set password='#{newPassword}'where manager=#{manager}")
    void updataPassword(@Param(value = "manager") String manager,@Param(value = "newPassword") String newPassword);

    @Delete("delete from user where userid=#{userid}")
    void deleteUser(@Param(value = "userid")Integer userid);
}