package com.wncg.dao;

import com.wncg.po.SearchRecord;
import com.wncg.po.SearchRecordExample;
import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface SearchRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    int countByExample(SearchRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    int deleteByExample(SearchRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    int deleteByPrimaryKey(Integer searchId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    int insert(SearchRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    int insertSelective(SearchRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    List<SearchRecord> selectByExample(SearchRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    SearchRecord selectByPrimaryKey(Integer searchId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") SearchRecord record, @Param("example") SearchRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    int updateByExample(@Param("record") SearchRecord record, @Param("example") SearchRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    int updateByPrimaryKeySelective(SearchRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    int updateByPrimaryKey(SearchRecord record);

    //以下代码由用户创建

    //查询搜索内容是否存在
    @Select("select * from search_record where search_content = #{bookName} and user_id = #{userId}")
    List<SearchRecord> selectRecord(@Param(value = "bookName") String bookName, @Param(value = "userId") Integer userId);

    //增加搜索内容
    @Insert("insert into search_record (user_id,search_content) values (#{userId}, #{bookName})")
    void insertSearchRecord(@Param(value = "bookName") String bookName, @Param(value = "userId") Integer userId);

    //通过userId查询搜素历史
    @Select("select search_id,search_content from search_record where user_id = #{userId}")
    List<SearchRecord> selectByUserId(Integer userId);
}