package com.wncg.po;

public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_id
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    private String bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.subject_id
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    private Integer subjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.isbn
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    private String isbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_name
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    private String bookName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.alpha
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    private String alpha;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.phoneticize
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    private String phoneticize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_type
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    private String bookType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.author
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.press
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    private String press;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.version_number
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    private String versionNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.quantity
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    private Integer quantity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_id
     *
     * @return the value of book.book_id
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public String getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_id
     *
     * @param bookId the value for book.book_id
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public void setBookId(String bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.subject_id
     *
     * @return the value of book.subject_id
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.subject_id
     *
     * @param subjectId the value for book.subject_id
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.isbn
     *
     * @return the value of book.isbn
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.isbn
     *
     * @param isbn the value for book.isbn
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_name
     *
     * @return the value of book.book_name
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_name
     *
     * @param bookName the value for book.book_name
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.alpha
     *
     * @return the value of book.alpha
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public String getAlpha() {
        return alpha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.alpha
     *
     * @param alpha the value for book.alpha
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public void setAlpha(String alpha) {
        this.alpha = alpha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.phoneticize
     *
     * @return the value of book.phoneticize
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public String getPhoneticize() {
        return phoneticize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.phoneticize
     *
     * @param phoneticize the value for book.phoneticize
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public void setPhoneticize(String phoneticize) {
        this.phoneticize = phoneticize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_type
     *
     * @return the value of book.book_type
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public String getBookType() {
        return bookType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_type
     *
     * @param bookType the value for book.book_type
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public void setBookType(String bookType) {
        this.bookType = bookType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.author
     *
     * @return the value of book.author
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.author
     *
     * @param author the value for book.author
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.press
     *
     * @return the value of book.press
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public String getPress() {
        return press;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.press
     *
     * @param press the value for book.press
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public void setPress(String press) {
        this.press = press;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.version_number
     *
     * @return the value of book.version_number
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public String getVersionNumber() {
        return versionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.version_number
     *
     * @param versionNumber the value for book.version_number
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public void setVersionNumber(String versionNumber) {
        this.versionNumber = versionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.quantity
     *
     * @return the value of book.quantity
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.quantity
     *
     * @param quantity the value for book.quantity
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
}