package com.wncg.po;

public class BookWithBLOBs extends Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.cover
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    private byte[] cover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.preface
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    private String preface;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.contens
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    private String contens;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.briefin_troduction
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    private String briefinTroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_review
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    private String bookReview;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.introduction
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    private String introduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.cover
     *
     * @return the value of book.cover
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public byte[] getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.cover
     *
     * @param cover the value for book.cover
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public void setCover(byte[] cover) {
        this.cover = cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.preface
     *
     * @return the value of book.preface
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public String getPreface() {
        return preface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.preface
     *
     * @param preface the value for book.preface
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public void setPreface(String preface) {
        this.preface = preface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.contens
     *
     * @return the value of book.contens
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public String getContens() {
        return contens;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.contens
     *
     * @param contens the value for book.contens
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public void setContens(String contens) {
        this.contens = contens;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.briefin_troduction
     *
     * @return the value of book.briefin_troduction
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public String getBriefinTroduction() {
        return briefinTroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.briefin_troduction
     *
     * @param briefinTroduction the value for book.briefin_troduction
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public void setBriefinTroduction(String briefinTroduction) {
        this.briefinTroduction = briefinTroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_review
     *
     * @return the value of book.book_review
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public String getBookReview() {
        return bookReview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_review
     *
     * @param bookReview the value for book.book_review
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public void setBookReview(String bookReview) {
        this.bookReview = bookReview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.introduction
     *
     * @return the value of book.introduction
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.introduction
     *
     * @param introduction the value for book.introduction
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }
}