package com.wncg.po;

public class Manager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.manager_id
     *
     * @mbggenerated Sun Apr 09 15:46:46 CST 2017
     */
    private Integer managerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.manager
     *
     * @mbggenerated Sun Apr 09 15:46:46 CST 2017
     */
    private String manager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.password
     *
     * @mbggenerated Sun Apr 09 15:46:46 CST 2017
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.manager_id
     *
     * @return the value of manager.manager_id
     *
     * @mbggenerated Sun Apr 09 15:46:46 CST 2017
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.manager_id
     *
     * @param managerId the value for manager.manager_id
     *
     * @mbggenerated Sun Apr 09 15:46:46 CST 2017
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.manager
     *
     * @return the value of manager.manager
     *
     * @mbggenerated Sun Apr 09 15:46:46 CST 2017
     */
    public String getManager() {
        return manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.manager
     *
     * @param manager the value for manager.manager
     *
     * @mbggenerated Sun Apr 09 15:46:46 CST 2017
     */
    public void setManager(String manager) {
        this.manager = manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.password
     *
     * @return the value of manager.password
     *
     * @mbggenerated Sun Apr 09 15:46:46 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.password
     *
     * @param password the value for manager.password
     *
     * @mbggenerated Sun Apr 09 15:46:46 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }
}