package com.wncg.po;

public class SearchRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_record.search_id
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    private Integer searchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_record.user_id
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_record.search_content
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    private String searchContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_record.search_id
     *
     * @return the value of search_record.search_id
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public Integer getSearchId() {
        return searchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_record.search_id
     *
     * @param searchId the value for search_record.search_id
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public void setSearchId(Integer searchId) {
        this.searchId = searchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_record.user_id
     *
     * @return the value of search_record.user_id
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_record.user_id
     *
     * @param userId the value for search_record.user_id
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_record.search_content
     *
     * @return the value of search_record.search_content
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public String getSearchContent() {
        return searchContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_record.search_content
     *
     * @param searchContent the value for search_record.search_content
     *
     * @mbggenerated Tue Mar 14 14:26:49 CST 2017
     */
    public void setSearchContent(String searchContent) {
        this.searchContent = searchContent;
    }
}