package com.wncg.po;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userid
     *
     * @mbggenerated Sun Mar 12 20:01:37 CST 2017
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.wx_id
     *
     * @mbggenerated Sun Mar 12 20:01:37 CST 2017
     */
    private Integer wxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.tel
     *
     * @mbggenerated Sun Mar 12 20:01:37 CST 2017
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.rel_name
     *
     * @mbggenerated Sun Mar 12 20:01:37 CST 2017
     */
    private String relName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id_num
     *
     * @mbggenerated Sun Mar 12 20:01:37 CST 2017
     */
    private String idNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Sun Mar 12 20:01:37 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.register_time
     *
     * @mbggenerated Sun Mar 12 20:01:37 CST 2017
     */
    private Date registerTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userid
     *
     * @return the value of user.userid
     *
     * @mbggenerated Sun Mar 12 20:01:37 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userid
     *
     * @param userid the value for user.userid
     *
     * @mbggenerated Sun Mar 12 20:01:37 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.wx_id
     *
     * @return the value of user.wx_id
     *
     * @mbggenerated Sun Mar 12 20:01:37 CST 2017
     */
    public Integer getWxId() {
        return wxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.wx_id
     *
     * @param wxId the value for user.wx_id
     *
     * @mbggenerated Sun Mar 12 20:01:37 CST 2017
     */
    public void setWxId(Integer wxId) {
        this.wxId = wxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.tel
     *
     * @return the value of user.tel
     *
     * @mbggenerated Sun Mar 12 20:01:37 CST 2017
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.tel
     *
     * @param tel the value for user.tel
     *
     * @mbggenerated Sun Mar 12 20:01:37 CST 2017
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.rel_name
     *
     * @return the value of user.rel_name
     *
     * @mbggenerated Sun Mar 12 20:01:37 CST 2017
     */
    public String getRelName() {
        return relName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.rel_name
     *
     * @param relName the value for user.rel_name
     *
     * @mbggenerated Sun Mar 12 20:01:37 CST 2017
     */
    public void setRelName(String relName) {
        this.relName = relName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id_num
     *
     * @return the value of user.id_num
     *
     * @mbggenerated Sun Mar 12 20:01:37 CST 2017
     */
    public String getIdNum() {
        return idNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id_num
     *
     * @param idNum the value for user.id_num
     *
     * @mbggenerated Sun Mar 12 20:01:37 CST 2017
     */
    public void setIdNum(String idNum) {
        this.idNum = idNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Sun Mar 12 20:01:37 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Sun Mar 12 20:01:37 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.register_time
     *
     * @return the value of user.register_time
     *
     * @mbggenerated Sun Mar 12 20:01:37 CST 2017
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.register_time
     *
     * @param registerTime the value for user.register_time
     *
     * @mbggenerated Sun Mar 12 20:01:37 CST 2017
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }
}